# Configuração Universal de ETL para APIs
#
# Estrutura:
# [nome_api]
# base_url = "https://..."
#
# [nome_api.endpoints.nome_grupo]
# root_path = "chave_raiz"
# chave_endpoint = "/caminho"



#Compras
[compras_federal]
base_url = "https://dadosabertos.compras.gov.br"

[compras_federal.endpoints.material]
root_path = "resultado"
grupo = "/modulo-material/1_consultarGrupoMaterial"
classe = "/modulo-material/2_consultarClasseMaterial"
pdm = "/modulo-material/3_consultarPdmMaterial"
item = "/modulo-material/4_consultarItemMaterial"
natureza_despesa = "/modulo-material/5_consultarMaterialNaturezaDespesa"
unidade_fornecimento = "/modulo-material/6_consultarMaterialUnidadeFornecimento"
caracteristicas = "/modulo-material/7_consultarMaterialCaracteristicas"

[compras_federal.endpoints.servico]
root_path = "resultado"
secao = "/modulo-servico/1_consultarSecaoServico"
divisao = "/modulo-servico/2_consultarDivisaoServico"
grupo = "/modulo-servico/3_consultarGrupoServico"
classe = "/modulo-servico/4_consultarClasseServico"
subclasse = "/modulo-servico/5_consultarSubClasseServico"
item = "/modulo-servico/6_consultarItemServico"
unidade_medida = "/modulo-servico/7_consultarUndMedidaServico"
natureza_despesa = "/modulo-servico/8_consultarNaturezaDespesaServico"

[compras_federal.endpoints.pesquisa_preco]
root_path = "resultado"
material_json = "/modulo-pesquisa-preco/1_consultarMaterial"
servico_json = "/modulo-pesquisa-preco/3_consultarServico"
servico_detalhe_json = "/modulo-pesquisa-preco/4_consultarServicoDetalhe"

[compras_federal.endpoints.pgc]
root_path = "resultado"
detalhe = "/modulo-pgc/1_consultarPgcDetalhe"
catalogo = "/modulo-pgc/2_consultarPgcDetalheCatalogo"
agregacao = "/modulo-pgc/3_consultarPgcAgregacao"

[compras_federal.endpoints.uasg]
root_path = "resultado"
consulta = "/modulo-uasg/1_consultarUasg"
orgao = "/modulo-uasg/2_consultarOrgao"

[compras_federal.endpoints.legado]
root_path = "resultado"
licitacao = "/modulo-legado/1_consultarLicitacao"
licitacao_id = "/modulo-legado/1.1_consultarLicitacao_Id"
item_licitacao = "/modulo-legado/2_consultarItemLicitacao"
item_licitacao_id = "/modulo-legado/2.1_consultarItemLicitacao_Id"
pregoes = "/modulo-legado/3_consultarPregoes"
pregoes_id = "/modulo-legado/3.1_consultarPregoes_Id"
pregoes_itens = "/modulo-legado/4_consultarItensPregoes"
pregoes_itens_id = "/modulo-legado/4.1_consultarItensPregoes_Id"
sem_licitacao = "/modulo-legado/5_consultarComprasSemLicitacao"
sem_licitacao_id = "/modulo-legado/5.1_consultarCompraSemLicitacao_Id"
sem_licitacao_itens = "/modulo-legado/6_consultarCompraItensSemLicitacao"
sem_licitacao_itens_id = "/modulo-legado/6.1_consultarItensComprasSemLicitacao_Id"
rdc = "/modulo-legado/7_consultarRdc"

[compras_federal.endpoints.pncp]
root_path = "resultado"
contratacoes = "/modulo-contratacoes/1_consultarContratacoes_PNCP_14133"
contratacoes_id = "/modulo-contratacoes/1.1_consultarContratacoes_PNCP_14133_Id"
itens = "/modulo-contratacoes/2_consultarItensContratacoes_PNCP_14133"
itens_id = "/modulo-contratacoes/2.1_consultarItensContratacoes_PNCP_14133_Id"
resultado = "/modulo-contratacoes/3_consultarResultadoItensContratacoes_PNCP_14133"
resultado_id = "/modulo-contratacoes/3.1_consultarResultadoItensContratacoes_PNCP_14133_Id"

[compras_federal.endpoints.arp]
root_path = "resultado"
consulta = "/modulo-arp/1_consultarARP"
consulta_id = "/modulo-arp/1.1_consultarARP_Id"
fim_vigencia = "/modulo-arp/1.2_consultarARP_FimVigencia"
item = "/modulo-arp/2_consultarARPItem"
item_id = "/modulo-arp/2.1_consultarARPItem_Id"
unidades_item = "/modulo-arp/3_consultarUnidadesItem"
saldo_item = "/modulo-arp/4_consultarEmpenhosSaldoItem"
adesoes_item = "/modulo-arp/5_consultarAdesoesItem"

[compras_federal.endpoints.contratos]
root_path = "resultado"
consulta = "/modulo-contratos/1_consultarContratos"
consulta_id = "/modulo-contratos/1.1_consultarContratos_Id"
fim_vigencia = "/modulo-contratos/1.2_consultarContratos_FimVigencia"
item = "/modulo-contratos/2_consultarContratosItem"
item_id = "/modulo-contratos/2.1_consultarContratosItem_Id"

[compras_federal.endpoints.outros]
root_path = "resultado"
fornecedor = "/modulo-fornecedor/1_consultarFornecedor"
ocds = "/modulo-ocds/1_releases"

[compras_federal.endpoints.alice]
root_path = "resultado"
avisos_restritos = "/alice/avisos-restritos"
compras = "/alice/compras"
tickets = "/alice/tickets"


# Câmara dos Deputados
[camara_deputados]
base_url = "https://dadosabertos.camara.leg.br/api/v2"

[camara_deputados.endpoints.geral]
root_path = "dados"
lista_deputados = "/deputados"
votacoes = "/votacoes"
orgaos = "/orgaos"
partidos = "/partidos"
legislatura = "/legislaturas"
blocos = "/blocos"
frentes = "/frentes"
grupos = "/grupos"
eventos = "/eventos"
referencias = "/referencias"
lideres = "/lideres"

[camara_deputados.endpoints.proposicoes]
root_path = "dados"
busca = "/proposicoes"
detalhe = "/proposicoes/{id}"
autores = "/proposicoes/{id}/autores"
relacionadas = "/proposicoes/{id}/relacionadas"
temas = "/proposicoes/{id}/temas"
tramitacoes = "/proposicoes/{id}/tramitacoes"
votacoes = "/proposicoes/{id}/votacoes"

[camara_deputados.endpoints.votacoes]
root_path = "dados"
busca = "/votacoes"
detalhe = "/votacoes/{id}"
orientacoes = "/votacoes/{id}/orientacoes"
votos = "/votacoes/{id}/votos"

[camara_deputados.endpoints.orgaos]
root_path = "dados"
busca = "/orgaos"
detalhe = "/orgaos/{id}"
eventos = "/orgaos/{id}/eventos"
membros = "/orgaos/{id}/membros"
votacoes = "/orgaos/{id}/votacoes"

[camara_deputados.endpoints.referencias_proposicoes]
root_path = "dados"
cod_situacao = "/referencias/proposicoes/codSituacao"
cod_tema = "/referencias/proposicoes/codTema"
cod_tipo_autor = "/referencias/proposicoes/codTipoAutor"
cod_tipo_tramitacao = "/referencias/proposicoes/codTipoTramitacao"
sigla_tipo = "/referencias/proposicoes/siglaTipo"
situacoes_proposicao = "/referencias/situacoesProposicao"
tipos_autor = "/referencias/tiposAutor"
tipos_proposicao = "/referencias/tiposProposicao"
tipos_tramitacao = "/referencias/tiposTramitacao"

[camara_deputados.endpoints.referencias_orgaos]
root_path = "dados"
cod_situacao = "/referencias/orgaos/codSituacao"
situacoes_orgao = "/referencias/situacoesOrgao"